const MODEL_OPTIONS = ['X990', 'A910', 'A910S', 'A99'];
const ANDROID_OPTIONS = ['6', '7', '10', '12', '14'];
const state = { appsConfig: [], whiteListPackageName: '', imageConfig: { config: [], timeStamp: '' }, pfxConfig: { pfxFileName: '', timeStamp: '' }, bannerConfig: [], supportConfig: { timeStamp: '', helpLine: '', preAuth: { dateExceededMessage: '', amountLimitMessage: '', completionReminderMessage: '' } } };
const $ = id => document.getElementById(id);
const escapeHtml = value => String(value ?? '').replace(/[&<>\"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
function createChecks(container, values, prefix) { container.innerHTML = values.map((v,i) => `<label class="check-item"><input type="checkbox" id="${prefix}-${i}" value="${escapeHtml(v)}"><span>${escapeHtml(v)}</span></label>`).join(''); }
function checkedValues(id) { return [...document.querySelectorAll(`#${id} input:checked`)].map(i => i.value); }
function setChecked(id, values) { const set = new Set(values || []); document.querySelectorAll(`#${id} input`).forEach(i => i.checked = set.has(i.value)); }
function customValuesFromUi(id) { return [...document.querySelectorAll(`#${id} .custom-chip`)].map(x => x.dataset.value); }
function renderCustomList(id, values, prefix) { $(id).innerHTML = (values || []).map(v => `<span class="custom-chip" data-value="${escapeHtml(v)}">${escapeHtml(v)} <button type="button" data-remove-custom="${prefix}" data-value="${escapeHtml(v)}">×</button></span>`).join(''); }
function allTargetValues(checkId, customId) { return [...new Set([...checkedValues(checkId), ...customValuesFromUi(customId)])]; }
function addCustomValue(inputId,listId) { const value=$(inputId).value.trim(); if(!value)return; const values=customValuesFromUi(listId); if(!values.includes(value))values.push(value); renderCustomList(listId,values,inputId==='customModel'?'model':'android'); $(inputId).value=''; }
function toggleOther(rowId,inputId){ $(rowId).classList.toggle('hidden'); if(!$(rowId).classList.contains('hidden'))$(inputId).focus(); }
function normalizeApp(app={}){return{title:app.title||'',appName:app.appName||'',packageName:app.packageName||'',appVersion:app.appVersion||'',revisionId:app.revisionId||'',isMandatoy:app.isMandatoy??app.mandatory??true,availabilityType:Number(app.availabilityType??0),tids:Array.isArray(app.tids)?app.tids:[],isDelete:app.isDelete??false,deleteType:Number(app.deleteType??0),deleteTids:Array.isArray(app.deleteTids)?app.deleteTids:[],modelName:Array.isArray(app.modelName)?app.modelName:(app.models||[]),androidVersion:Array.isArray(app.androidVersion)?app.androidVersion:(app.androidVersions||[]),autoInstall:app.autoInstall??false,dependency:Array.isArray(app.dependency)?app.dependency.map(d=>({appName:d.appName||'',packageName:d.packageName||'',appVersion:d.appVersion||''})):[]};}
function getAppKey(app){return`${app.packageName}|${app.appVersion}`;}
function isDependencyOfAnotherApp(index){const target=state.appsConfig[index];if(!target)return false;const key=getAppKey(target);return state.appsConfig.some((app,i)=>i!==index&&(app.dependency||[]).some(d=>`${d.packageName}|${d.appVersion}`===key));}
function getLinkedDependencyNames(index){const key=getAppKey(state.appsConfig[index]||{});return state.appsConfig.filter((_,i)=>i!==index).filter(app=>(app.dependency||[]).some(d=>`${d.packageName}|${d.appVersion}`===key)).map(app=>app.title||app.appName);}
function enforceDependencyAutoInstall(){const keys=new Set();state.appsConfig.forEach(a=>(a.dependency||[]).forEach(d=>keys.add(`${d.packageName}|${d.appVersion}`)));state.appsConfig.forEach(a=>{if(keys.has(getAppKey(a)))a.autoInstall=false;});}
function buildOutput(){enforceDependencyAutoInstall();return{isRunOnBackground:$('runBackground').checked,isConfirmationRequired:$('confirmation').checked,isShowErrorMsg:$('showError').checked,isDownloadOverWifiOnly:$('wifiOnly').checked,appsConfig:state.appsConfig.map(normalizeApp),whiteListPackageName:state.whiteListPackageName,imageConfig:state.imageConfig,pfxConfig:state.pfxConfig,bannerConfig:state.bannerConfig,supportConfig:state.supportConfig};}
function refreshPreview(){$('jsonPreview').value=JSON.stringify(buildOutput(),null,4);}
function renderApps(){enforceDependencyAutoInstall();const c=$('appsContainer');if(!state.appsConfig.length){c.innerHTML='<div class="empty">No applications added yet. Click <b>+ Add Application</b>.</div>';return;}c.innerHTML=state.appsConfig.map((app,index)=>{const dep=isDependencyOfAnotherApp(index),linked=getLinkedDependencyNames(index),tid=app.isDelete&&app.deleteType===1?` · Delete TIDs: ${app.deleteTids.length}`:(app.availabilityType===1?` · TIDs: ${app.tids.length}`:'');const linkedInfo=linked.length?`<div class="dependency-link">Used as dependency by: <b>${linked.map(escapeHtml).join(', ')}</b></div>`:'';const mandatoryBadge=app.isMandatoy?'<span class="badge green">Mandatory</span>':'<span class="badge">Confirmation Required</span>';const autoInstallBadge=app.autoInstall?'<span class="badge">Auto Install</span>':'';return`<div class="app-row"><div class="app-main"><div class="app-title">${escapeHtml(app.title||app.appName)}</div><div class="app-meta">${escapeHtml(app.packageName)} · v${escapeHtml(app.appVersion)}${app.revisionId?` · Revision ${escapeHtml(app.revisionId)}`:''}${tid}</div>${linkedInfo}<div class="badges">${mandatoryBadge}${autoInstallBadge}${app.isDelete?'<span class="badge">Delete</span>':''}${dep?'<span class="badge green">Dependency</span>':''}${app.modelName.map(m=>`<span class="badge">${escapeHtml(m)}</span>`).join('')}${app.androidVersion.map(v=>`<span class="badge">Android ${escapeHtml(v)}</span>`).join('')}</div></div><div class="app-actions"><button data-action="edit" data-index="${index}">Edit</button><button data-action="clone" data-index="${index}">Clone</button><button data-action="delete" data-index="${index}">Delete</button></div></div>`;}).join('');}
function resetForm(){$('appForm').reset();$('editIndex').value='-1';$('modalTitle').textContent='Add Application';$('saveAppBtn').textContent='Save Application';$('formError').classList.add('hidden');setChecked('modelOptions',[]);setChecked('androidOptions',[]);$('tids').value='';$('deleteType').value='0';$('tidSection').classList.add('hidden');$('deleteTypeSection').classList.add('hidden');$('autoInstall').disabled=false;$('customModelRow').classList.add('hidden');$('customAndroidRow').classList.add('hidden');renderCustomList('customModelList',[],'model');renderCustomList('customAndroidList',[],'android');updateDependencyOptions();}
function openModal(index=-1){resetForm();if(index>=0){const app=state.appsConfig[index];$('editIndex').value=String(index);$('modalTitle').textContent='Edit Application';$('saveAppBtn').textContent='Update Application';$('title').value=app.title;$('appName').value=app.appName;$('packageName').value=app.packageName;$('appVersion').value=app.appVersion;$('revisionId').value=app.revisionId;$('mandatory').checked=!!app.isMandatoy;$('autoInstall').checked=!!app.autoInstall;$('isDelete').checked=!!app.isDelete;$('availabilityType').value=String(app.availabilityType);$('deleteType').value=String(app.deleteType);$('tids').value=app.isDelete?app.deleteTids.join('\n'):app.tids.join('\n');setChecked('modelOptions',app.modelName);setChecked('androidOptions',app.androidVersion);const cm=app.modelName.filter(v=>!MODEL_OPTIONS.includes(v)),ca=app.androidVersion.filter(v=>!ANDROID_OPTIONS.includes(v));renderCustomList('customModelList',cm,'model');renderCustomList('customAndroidList',ca,'android');if(cm.length)$('customModelRow').classList.remove('hidden');if(ca.length)$('customAndroidRow').classList.remove('hidden');updateDependencyOptions(app.dependency);updateModeVisibility();updateAutoInstallControl(index);}$('appModal').classList.remove('hidden');$('title').focus();}
function updateAutoInstallControl(index){const dep=isDependencyOfAnotherApp(index);$('autoInstall').disabled=dep;if(dep)$('autoInstall').checked=false;}
function updateModeVisibility(){const del=$('isDelete').checked;$('availabilitySection').classList.toggle('hidden',del);$('deleteTypeSection').classList.toggle('hidden',!del);const type=Number(del?$('deleteType').value:$('availabilityType').value);$('tidSection').classList.toggle('hidden',type!==1);}
function updateDependencyOptions(selected=[]){const c=$('dependencyOptions'),set=new Set(selected.map(d=>`${d.packageName}|${d.appVersion}`)),current=Number($('editIndex').value),candidates=state.appsConfig.filter((_,i)=>i!==current);if(!candidates.length){c.innerHTML='<div class="empty">Add other applications first to configure dependencies.</div>';return;}c.innerHTML=candidates.map(app=>{const key=getAppKey(app);return`<label class="dependency-row"><input type="checkbox" value="${escapeHtml(key)}" data-app-name="${escapeHtml(app.appName)}" data-package="${escapeHtml(app.packageName)}" data-version="${escapeHtml(app.appVersion)}" ${set.has(key)?'checked':''}><span><b>${escapeHtml(app.title||app.appName)}</b> — ${escapeHtml(app.packageName)} — ${escapeHtml(app.appVersion)}</span></label>`}).join('');}
function getDependencies(){return[...document.querySelectorAll('#dependencyOptions input:checked')].map(i=>({appName:i.dataset.appName,packageName:i.dataset.package,appVersion:i.dataset.version}));}
function saveApp(){const title=$('title').value.trim(),appName=$('appName').value.trim(),packageName=$('packageName').value.trim(),appVersion=$('appVersion').value.trim();if(!title||!appName||!packageName||!appVersion){$('formError').textContent='Title, App Name, Package Name and App Version are required.';$('formError').classList.remove('hidden');return;}const del=$('isDelete').checked,type=Number(del?$('deleteType').value:$('availabilityType').value),tids=$('tids').value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);const app=normalizeApp({title,appName,packageName,appVersion,revisionId:$('revisionId').value.trim(),isMandatoy:$('mandatory').checked,availabilityType:del?0:type,tids:!del&&type===1?tids:[],isDelete:del,deleteType:del?type:0,deleteTids:del&&type===1?tids:[],modelName:allTargetValues('modelOptions','customModelList'),androidVersion:allTargetValues('androidOptions','customAndroidList'),autoInstall:$('autoInstall').disabled?false:$('autoInstall').checked,dependency:getDependencies()});const index=Number($('editIndex').value);if(index>=0)state.appsConfig[index]=app;else state.appsConfig.push(app);enforceDependencyAutoInstall();renderApps();refreshPreview();closeModal();toast(index>=0?'Application updated':'Application added');}
function closeModal(){$('appModal').classList.add('hidden');}
function toast(message){const e=$('toast');e.textContent=message;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),1800);}
function importJson(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);$('runBackground').checked=!!d.isRunOnBackground;$('confirmation').checked=!!d.isConfirmationRequired;$('showError').checked=!!d.isShowErrorMsg;$('wifiOnly').checked=!!d.isDownloadOverWifiOnly;state.appsConfig=Array.isArray(d.appsConfig)?d.appsConfig.map(normalizeApp):[];state.whiteListPackageName=d.whiteListPackageName||'';state.imageConfig=d.imageConfig||{config:[],timeStamp:''};state.pfxConfig=d.pfxConfig||{pfxFileName:'',timeStamp:''};state.bannerConfig=Array.isArray(d.bannerConfig)?d.bannerConfig:[];state.supportConfig=d.supportConfig||state.supportConfig;enforceDependencyAutoInstall();renderApps();refreshPreview();toast(`Imported ${state.appsConfig.length} application(s)`);}catch{toast('Invalid JSON file');}};r.readAsText(file);}
function downloadJson(){const blob=new Blob([JSON.stringify(buildOutput(),null,4)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='appstore-config.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('JSON downloaded');}
createChecks($('modelOptions'),MODEL_OPTIONS,'model');createChecks($('androidOptions'),ANDROID_OPTIONS,'android');renderApps();refreshPreview();
['runBackground','confirmation','showError','wifiOnly'].forEach(id=>$(id).addEventListener('change',refreshPreview));
$('addAppBtn').addEventListener('click',()=>openModal());$('closeModalBtn').addEventListener('click',closeModal);$('cancelBtn').addEventListener('click',closeModal);$('saveAppBtn').addEventListener('click',saveApp);$('isDelete').addEventListener('change',updateModeVisibility);$('availabilityType').addEventListener('change',updateModeVisibility);$('deleteType').addEventListener('change',updateModeVisibility);
$('otherModelBtn').addEventListener('click',()=>toggleOther('customModelRow','customModel'));$('otherAndroidBtn').addEventListener('click',()=>toggleOther('customAndroidRow','customAndroid'));$('addModelBtn').addEventListener('click',()=>addCustomValue('customModel','customModelList'));$('addAndroidBtn').addEventListener('click',()=>addCustomValue('customAndroid','customAndroidList'));
$('customModel').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustomValue('customModel','customModelList');}});$('customAndroid').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCustomValue('customAndroid','customAndroidList');}});
$('customModelList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-custom]');if(b){renderCustomList('customModelList',customValuesFromUi('customModelList').filter(v=>v!==b.dataset.value),'model');}});$('customAndroidList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-custom]');if(b){renderCustomList('customAndroidList',customValuesFromUi('customAndroidList').filter(v=>v!==b.dataset.value),'android');}});
$('importBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value='';});$('downloadBtn').addEventListener('click',downloadJson);$('copyBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('jsonPreview').value);toast('JSON copied');}catch{toast('Copy failed');}});
$('newBtn').addEventListener('click',()=>{state.appsConfig=[];state.whiteListPackageName='';state.imageConfig={config:[],timeStamp:''};state.pfxConfig={pfxFileName:'',timeStamp:''};state.bannerConfig=[];state.supportConfig={timeStamp:'',helpLine:'',preAuth:{dateExceededMessage:'',amountLimitMessage:'',completionReminderMessage:''}};$('runBackground').checked=false;$('confirmation').checked=false;$('showError').checked=false;$('wifiOnly').checked=false;renderApps();refreshPreview();toast('New configuration created');});
$('appsContainer').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const i=Number(b.dataset.index),a=b.dataset.action;if(a==='edit')openModal(i);if(a==='clone'){const c=structuredClone(state.appsConfig[i]);c.title=`${c.title} Copy`;state.appsConfig.splice(i+1,0,c);enforceDependencyAutoInstall();renderApps();refreshPreview();toast('Application cloned');}if(a==='delete'&&confirm(`Delete ${state.appsConfig[i].title||state.appsConfig[i].appName}?`)){state.appsConfig.splice(i,1);enforceDependencyAutoInstall();renderApps();refreshPreview();toast('Application deleted');}});
$('appModal').addEventListener('click',e=>{if(e.target===$('appModal'))closeModal();});
